version: "3.9"
services:
  db:
    image: postgres:15
    container_name: daggerheart-db
    restart: always
    environment:
      POSTGRES_DB: characters
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: shutup
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d characters" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/characters
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: shutup
volumes:
  postgres_data:
